
    - name: Install slack
      homebrew_cask: name=slack

    - name: Install docker
      homebrew: name=docker

    - name: Install tmux
      homebrew: name=tmux

    - name: Install IntelliJ
      homebrew_cask: name=intellij-idea

    - name: Install homebrew versions
      homebrew_tap: tap=homebrew/versions
