- name: Install PlantUML CLI diagramming tool
  homebrew: name=plantuml

- name: Install vim text editor
  homebrew: name=vim

- name: Setup paths for vim
  file: path={{ item }} state=directory
  with_items:
  - ~/.vim/autoload
  - ~/.vim/bundle

- name: Install pathogen vim plugin/configuration manager
  get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

- name: Install vim plugin
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
  with_items:
  - {repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree}
  - {repo: "https://github.com/Xuyuanp/nerdtree-git-plugin.git", name: nerdtree-git-plugin}
  - {repo: "https://github.com/ctrlpvim/ctrlp.vim.git", name: ctrlp}
  - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", name: vim-better-whitespace}
  - {repo: "https://github.com/airblade/vim-gitgutter.git", name: vim-gitgutter}
  - {repo: "https://github.com/plasticboy/vim-markdown.git", name: vim-markdown}
  - {repo: "https://github.com/IN3D/vim-raml.git", name: vim-raml}
  - {repo: "https://github.com/Valloric/YouCompleteMe.git", name: YouCompleteMe}
  - {repo: "https://github.com/aklt/plantuml-syntax.git", name: plantuml-syntax}

- name: Update .vimrc
  lineinfile: dest=~/.vimrc line={{ item }} create=yes
  with_items:
  - execute pathogen#infect()
  - syntax on
  - filetype plugin indent on
  - :set tabstop=2
  - :set shiftwidth=2
  - :set backspace=indent,eol,start
  - :set expandtab
  - :set nobackup
  - :set noswapfile
  - let g:ctrlp_map = '<c-p>'
  - let g:ctrlp_cmd = 'CtrlP'
  - map <C-n> :NERDTreeToggle<CR>
  - autocmd BufEnter * EnableStripWhitespaceOnSave

- name: Install YouCompleteMe
  shell: ./install.py chdir=~/.vim/bundle/YouCompleteMe

- name: Install IntelliJ
  homebrew_cask: name=intellij-idea

- name: Install lynx command line browser
  homebrew: name=lynx

- name: Install Chrome browser
  homebrew_cask: name=google-chrome

- name: Install Taskwarrior command line task management tool
  homebrew: name=task

- name: Install 1Password password manager
  homebrew_cask: name=1password
