
    - name: Install git source control
      homebrew: name=git

    - name: Install bash-completion
      homebrew: name=bash-completion

    - name: Setup bash-completion
      blockinfile:
        path: ~/.bash_profile
        block: |
          if [ -f $(brew --prefix)/etc/bash_completion ]; then
            . $(brew --prefix)/etc/bash_completion
          fi

    - name: Setup terminal for git
      blockinfile:
        path: ~/.bash_profile
        block: |
          source /usr/local/etc/bash_completion.d/git-prompt.sh
          GIT_PS1_SHOWDIRTYSTATE=true
          export PS1='[\u@mbp \w$(__git_ps1)]\$ '

    - name: Setup git colors
      blockinfile:
        path: ~/.gitconfig
        block: |
          [color]
                  branch = auto
                  diff = auto
                  status = auto
          [color "branch"]
                  current = yellow reverse
                  local = yellow
                  remote = green
          [color "diff"]
                  meta = yellow bold
                  frag = magenta bold
                  old = red bold
                  new = green bold
          [color "status"]
                  added = yellow
                  changed = green
                  untracked = cyan

    - name: Install tmux terminal multiplexer
      homebrew: name=tmux

    - name: Install PlantUML CLI diagramming tool
      homebrew: name=plantuml

    - name: Install vim text editor
      homebrew: name=vim

    - name: Setup paths for vim
      file: path={{ item }} state=directory
      with_items:
      - ~/.vim/autoload
      - ~/.vim/bundle

    - name: Install pathogen vim plugin/configuration manager
      get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

    - name: Install vim plugin
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
      - {repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree}
      - {repo: "https://github.com/ctrlpvim/ctrlp.vim.git", name: ctrlp}
      - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", name: vim-better-whitespace}
      - {repo: "https://github.com/airblade/vim-gitgutter.git", name: vim-gitgutter}
      - {repo: "https://github.com/aklt/plantuml-syntax.git", name: plantuml-syntax}

    - name: Update .vimrc
      lineinfile: dest=~/.vimrc line={{ item }} create=yes
      with_items:
      - execute pathogen#infect()
      - syntax on
      - filetype plugin indent on
      - :set tabstop=2
      - :set shiftwidth=2
      - :set backspace=indent,eol,start
      - :set expandtab
      - :set nobackup
      - :set noswapfile
      - let g:ctrlp_map = '<c-p>'
      - let g:ctrlp_cmd = 'CtrlP'
      - autocmd BufEnter * EnableStripWhitespaceOnSave

    - name: Install IntelliJ
      homebrew_cask: name=intellij-idea

    - name: Install icdiff side-by-side diff tool
      homebrew: name=icdiff

    - name: Install HTTPie cURL wrapper
      homebrew: name=httpie

    - name: Install lynx command line browser
      homebrew: name=lynx

    - name: Install Chrome browser
      homebrew_cask: name=google-chrome

    - name: Install 1Password password manager
      homebrew_cask: name=1password

    - name: Install Alfred productivity utility
      homebrew_cask: name=alfred

    - name: Install Taskwarrior command line task management tool
      homebrew: name=task

    - name: Install Dropbox for online storage
      homebrew_cask: name=dropbox

    - name: Install FUSE for extending native file handling capabilities
      homebrew_cask: name=osxfuse

    - name: Install FUSE NTFS support
      homebrew: name=ntfs-3g

    - name: Add /usr/local/sbin to path
      lineinfile: path=/etc/paths line='/usr/local/sbin' insertbefore='/usr/sbin'
      become: yes

    - name: Add drivers brew tap
      homebrew_tap: name=caskroom/drivers

    - name: Install logitech options software
      homebrew_cask: name=logitech-options

    - name: Install watch for repeating command line commands
      homebrew: name=watch
