
    - name: Install git source control
      homebrew: name=git

    - name: Install tmux terminal multiplexer
      homebrew: name=tmux

    - name: Install vim text editor
      homebrew: name=vim

    - name: Setup paths for vim
      file: path={{ item }} state=directory
      with_items:
      - ~/.vim/autoload
      - ~/.vim/bundle

    - name: Install pathogen vim plugin/configuration manager
      get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

    - name: Install vim plugin
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
      - {repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree}
      - {repo: "https://github.com/ctrlpvim/ctrlp.vim.git", name: ctrlp}
      - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", name: vim-better-whitespace}
      - {repo: "https://github.com/airblade/vim-gitgutter.git", name: vim-gitgutter}

    - name: Update .vimrc
      lineinfile: dest=~/.vimrc line={{ item }} create=yes
      with_items:
      - execute pathogen#infect()
      - syntax on
      - filetype plugin indent on
      - :set tabstop=2
      - :set shiftwidth=2
      - :set backspace=indent,eol,start
      - :set expandtab
      - :set nobackup
      - :set noswapfile
      - let g:ctrlp_map = '<c-p>'
      - let g:ctrlp_cmd = 'CtrlP'
      - autocmd BufEnter * EnableStripWhitespaceOnSave

    - name: Install icdiff side-by-side diff tool
      homebrew: name=icdiff

    - name: Install Chrome browser
      homebrew_cask: name=google-chrome

    - name: Install 1Password password manager
      homebrew_cask: name=1password

    - name: Install Alfred productivity utility
      homebrew_cask: name=alfred

    - name: Install Taskwarrior command line task management tool
      homebrew: name=task
