---
- hosts: all

  pre_tasks:

    - name: Add python3 as python to .bash_profile
      lineinfile: dest=~/.bash_profile line='alias python=/usr/local/bin/python3' create=yes

    - name: Add pip3 as pip to .bash_profile
      lineinfile: dest=~/.bash_profile line='alias pip=/usr/local/bin/pip3'

  roles:

    - source-control
    - office
    - configuration-management
