---
- hosts: all

  roles:

    - system
    - source-control
    - vim
    - java
    - dotnet
    - office
    - security
    - internet
    - configuration-management
    - clojure
    - ruby
    - node
    - media

  post_tasks:
    - name: Create remote user
      user: name=remote generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa shell=/bin/bash
      become: yes
