---
- hosts: all

  roles:

    - source-control
    - system
    - office
    - .
    - security
    - communication
    - configuration-management
    - java
    - clojure
    - ruby
    - node
    - media
