---
- hosts: all
  vars:
    shares:
    - Documents/workspace
    - Dropbox
    - .vagrant.d/boxes

  roles:

    - system
    - source-control
    - vim
    - java
    - dotnet
    - office
    - security
    - internet
    - configuration-management
    - clojure
    - ruby
    - node
    - media

  post_tasks:

    - name: Create remote user
      user: name=remote generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa shell=/bin/bash
      become: yes

    - name: Create remote user Documents directory
      file: path=/Users/remote/Documents state=directory owner=remote force=yes
      become: yes

    - name: Create symlink to shared directories for remote pair
      file: path=/Users/remote/{{ item }} src=/Users/{{ ansible_user }}/{{ item }} state=link owner=remote force=yes
      with_items: "{{ shares }}"
      become: yes
