---
- hosts: all

  roles:

    - source-control
    - vim
    - system
    - office
    - security
    - internet
    - configuration-management
    - java
    - clojure
    - ruby
    - node
    - media
