
    - name: Install tor anonymizing overlay network for TCP
      homebrew: name=tor

    - name: Install tor browser for anonymous web browsing
      homebrew_cask: name=torbrowser

    - name: Install nmap for network discovery and security auditing
      homebrew: name=nmap

    - name: Install dnsmap for brute force DNS name discovery
      homebrew: name=dnsmap

    - name: Install ncrack network authentication cracking tool
      homebrew: name=ncrack

    - name: Install skipfish web application security reconnaissance tool
      homebrew: name=skipfish

    - name: Install theHarvester e-mail account and subdomain discovery tool
      homebrew: name=theharvester

    - name: Install OWASP ZAP attack proxy
      homebrew_cask: name=owasp-zap
