
    - name: Install leiningen
      homebrew: name=leiningen

    - name: Install vim plugin
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
      - {repo: "https://github.com/tpope/vim-fireplace.git", name: vim-fireplace}
