- name: Install PlantUML CLI diagramming tool
  homebrew: name=plantuml

- name: Install IntelliJ
  homebrew_cask: name=intellij-idea

- name: Install Taskwarrior command line task management tool
  homebrew: name=task

- name: Install 1Password password manager
  homebrew_cask: name=1password
