- name: Install PlantUML CLI diagramming tool
  homebrew: name=plantuml

- name: Install jq command-line JSON processor
  homebrew: name=jq

- name: Install IntelliJ
  homebrew_cask: name=intellij-idea

- name: Install Taskwarrior command line task management tool
  homebrew: name=task

- name: Install 1Password password manager
  homebrew_cask: name=1password

- name: Install postman
  homebrew_cask: name=postman

- name: Install atom
  homebrew_cask: name=atom

- name: Install XmlStarlet
  homebrew: name=xmlstarlet

- name: Install yq XML/YAML query procesor
  homebrew: name=python-yq

- name: Install cloc lines of code utility
  homebrew: name=cloc
