
    - name: Install htop for process monitoring
      homebrew: name=htop

    - name: Install iftop for network monitoring
      homebrew: name=iftop

    - name: Install Wireshark packet analyzer
      homebrew_cask: name=wireshark
