
    - name: Install vim plugins
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
      with_items:
      - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
      - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
      - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}

    - name: Install docker
      homebrew_cask: name=docker

    - name: Install AWS CLI tools
      pip: name=awscli extra_args="--ignore-installed six"
      become: yes
