
    - name: Install jenv java environment manager
      homebrew: name=jenv

    - name: Add jenv to .bash_profile
      lineinfile: dest=~/.bash_profile line='{{ item }}' create=yes
      with_items:
      - export PATH="$HOME/.jenv/bin:$PATH"
      - eval "$(jenv init -)"

    - name: Install tap for Java
      homebrew_tap: tap=caskroom/versions

    - name: Install Java 8
      homebrew_cask: name=java8
