
    - name: Install nvm for node version management
      homebrew: name=nvm

    - name: Add nvm to .bash_profile
      lineinfile: dest=~/.bash_profile line='{{ item }}' create=yes
      with_items:
      - export NVM_DIR="$HOME/.nvm"
      - . "$(brew --prefix nvm)/nvm.sh"

    - name: Install Node.js
      shell: export NVM_DIR="$HOME/.nvm" && . "$(/usr/local/bin/brew --prefix nvm)/nvm.sh" && nvm install v10.16.3

    - name: Set default node version for NVM
      shell: export NVM_DIR="$HOME/.nvm" && . "$(/usr/local/bin/brew --prefix nvm)/nvm.sh" && nvm alias default node

    - name: Install Electron Packager
      shell: export NVM_DIR="$HOME/.nvm" && . "$(/usr/local/bin/brew --prefix nvm)/nvm.sh" && $HOME/.nvm/versions/node/v10.16.3/bin/npm install electron-packager@13.0.1 --global

    - name: Install Yarn
      shell: export NVM_DIR="$HOME/.nvm" && . "$(/usr/local/bin/brew --prefix nvm)/nvm.sh" && $HOME/.nvm/versions/node/v10.16.3/bin/npm install yarn@1.21.1 --global
