
    - name: Install nvm for node version management
      homebrew: name=nvm

    - name: Add nvm to .bash_profile
      lineinfile: dest=~/.bash_profile line='{{ item }}' create=yes
      with_items:
      - export NVM_DIR="$HOME/.nvm"
      - . "$(brew --prefix nvm)/nvm.sh"

    - name: Install Node.js
      shell: export NVM_DIR="$HOME/.nvm" && . "$(brew --prefix nvm)/nvm.sh" && nvm install v10.16.3

    - name: Install Electron Packager
      npm: name=electron-packager version=13.0.1 global=yes
      become: yes
